---
title: "DG_DESeq2_Fibrinogen"
author: "Slizovskiy Lab"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    fig_caption: true
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    theme: cosmo
---

```{r setup, include=FALSE}
# Base paths
base_dir  <- path.expand("G:/Shared drives/Microbiome_Inflammation_Study/GABRIELA_DATA_FILES/Cow_Inflammation_Study/DESeq2_Fibrinogen")
cache_dir <- file.path(base_dir, "Files", "Cache")
fig_dir   <- file.path(base_dir, "Figures")

# Create directories if they don't already exist
dir.create(cache_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(fig_dir,   recursive = TRUE, showWarnings = FALSE)

# Set knitr chunk options
knitr::opts_chunk$set(
  fig.keep       = "all",
  fig.path       = paste0(fig_dir, "/"),   # must end with slash
  dev = c("png", "svg"),        # <-- generate both PNG and SVG
  dpi = 300,
  cache          = TRUE,
  cache.lazy     = FALSE,
  cache.comments = FALSE,
  cache.path     = paste0(cache_dir, "/")
  )  # must end with slash

```

## Load libraries, phyloseq object, metadata

```{r message=FALSE, warning=FALSE}
# Load Required Packages
library(phyloseq)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(magrittr)
library(tibble)
library(microbiome)
library(ANCOMBC) # v2.8.1
library(lme4)
library(DESeq2)
library(EnhancedVolcano)
library(ggplot2)
library(pheatmap)
library(patchwork)
library(circlize)
library(ComplexHeatmap)

path.figures <- "G:/Shared drives/Microbiome_Inflammation_Study/GABRIELA_DATA_FILES/Cow_Inflammation_Study/DESeq2_Fibrinogen/Figures/"
path.rds <- "G:/Shared drives/Microbiome_Inflammation_Study/GABRIELA_DATA_FILES/Cow_Inflammation_Study"
```

```{r}
# Load phyloseq
ps <- readRDS(file.path(path.rds, "ps.st.decontam.rds"))
ps_feces <- subset_samples(ps, Sample_Type == "Feces")
ps_feces
saveRDS(ps_feces, file.path(path.rds, "ps.st.decontam.feces.rds"))
ps <- ps_feces
ps
```

```{r metadata}
# Update metadata ===================================
metadata <- read.csv(file.path(path.rds, "Updated_Cow_Metadata.csv"), 
                     stringsAsFactors = FALSE)
ps_samples <- sample_names(ps)
metadata <- metadata[metadata$Sample_ID %in% ps_samples, ]
rownames(metadata) <- metadata$Sample_ID
metadata$Sample_ID <- NULL
sample_data(ps) <- sample_data(metadata) # Assign metadata to the phyloseq obj

# Rename ASVs  ========================================
rename_asvs <- function(ps) {
  old_names <- taxa_names(ps)
  new_names <- paste0("ASV", seq_along(old_names))
  
  # Convert taxonomy to data frame
  tax_df <- as.data.frame(tax_table(ps))
  
  # Remove existing Sequence column if it exists
  if ("Sequence" %in% colnames(tax_df)) {
    tax_df <- tax_df[, !colnames(tax_df) %in% "Sequence", drop = FALSE]
  }
  
  # Add Sequence column at the beginning
  tax_df <- cbind(Sequence = old_names, tax_df)
  
  # Reassign to phyloseq object
  tax_table(ps) <- as.matrix(tax_df)
  taxa_names(ps) <- new_names
  
  return(ps)
}
ps <- rename_asvs(ps)
meta <- data.frame(sample_data(ps)) # Metadata after renaming

# Modify metadata  ===================================
meta$ExtractionDate <- as.Date(meta$ExtractionDate, format = "%m/%d/%Y")
meta$ExtractionDate_cat <- factor(meta$ExtractionDate)

meta$Parity_numeric <- as.numeric(as.character(meta$Parity))
meta$Parity_Group <- factor(ifelse(meta$Parity_numeric <= 3,"Group1", "Group2"))

meta$BCS <- as.numeric(as.character(meta$BCS))
meta$BCS_Group <- factor(cut(meta$BCS,
                             breaks = c(-Inf, 2.5, 3.5, Inf),
                             labels = c("Low", "Medium", "High"),
                             right = TRUE))

meta$Fibrinogen_InflamStat <- factor(meta$Fibrinogen_InflamStat, 
                                     levels = c("Normal", "Elevated"))
meta$Fibrinogen_InflamStat<- relevel(meta$Fibrinogen_InflamStat, ref = "Normal")

# Re-assign metadata to the phyloseq object  ===========
sample_data(ps) <- sample_data(meta)
dim(sample_data(ps))

# OTUs ==============================================
if (taxa_are_rows(ps)) {
  otu <- as(otu_table(ps), "matrix")   # already taxa x samples
} else {
  otu <- t(as(otu_table(ps), "matrix"))
}

# Align samples between counts and metadata
meta <- data.frame(sample_data(ps))
common_samples <- intersect(colnames(otu), rownames(meta))
otu  <- otu[, common_samples]
meta <- meta[common_samples, ]

# Check dimensions
cat("Samples in counts:", ncol(otu), "\n")
cat("Samples in metadata:", nrow(meta), "\n")
```

## DESeq2 handling zeros

```{r}
dds <- DESeqDataSetFromMatrix(
  countData = otu,
  colData   = meta,
  design    = ~ Fibrinogen_InflamStat + BCS_Group + Parity_Group + ExtractionDate_cat)

dds
dds$meta <- relevel(dds$Fibrinogen_InflamStat, ref = "Normal")
dds <- estimateSizeFactors(dds, type = "poscounts")

print("Size factors calculated:")
head(sizeFactors(dds))
```

Run DESeq2

```{r}
# dds <- DESeq(dds)
# saveRDS(dds, file.path(path.rds, "DeSeq_Fibrinogen/Files/DESeq_dds_Fibrino.rds"))
dds <- readRDS(file.path(path.rds, "DeSeq_Fibrinogen/Files/DESeq_dds_Fibrino.rds"))
dds

# Dispersion estimation
# dds_Fibrino_dispersion <- estimateDispersions(dds)
# saveRDS(dds_Fibrino_dispersion, file.path(path.rds, "DeSeq_Fibrinogen/Files/DESeq_dds_Fibrino_dispersion.rds"))
dds_Fibrino_dispersion <- readRDS(file.path(path.rds, "DeSeq_Fibrinogen/Files/DESeq_dds_Fibrino_dispersion.rds"))
plotDispEsts(dds)
```

Extract results:

```{r}
# Get results (change contrast to your comparison)
alpha <- 0.01
resultsNames(dds)
res<- results(dds, alpha = alpha, name = "Fibrinogen_InflamStat_Elevated_vs_Normal")
summary(res)

```

```{r}
# Make dataframe with taxonomy
res_df <- as.data.frame(res) %>%
  rownames_to_column("ASV") %>%
  filter(!is.na(padj)) %>%
  arrange(padj)

# Add taxonomy
tax_df <- as.data.frame(tax_table(ps)) %>%
  rownames_to_column("ASV")
res_df <- left_join(res_df, tax_df, by = "ASV")

# Significant results
sig_res <- filter(res_df, padj < 0.01)
sig_res <- sig_res[rowSums(otu[sig_res$ASV, ]) > 0, ]  # Remove zero-sum taxa

print(paste("Significant taxa:", nrow(sig_res)))

# Sort by p-value:
sig_res_sorted <- sig_res[order(sig_res$padj, -abs(sig_res$log2FoldChange)), ]

# Check
head(sig_res_sorted, 20)
summary(sig_res_sorted)

# Save
write.csv(sig_res_sorted,
  file.path(path.rds, "DeSeq_Fibrinogen/Files/result_Fibrino_annotated_sorted.csv"),
  row.names = FALSE)

```

Normalization using qPCR number
```{r normalization}
# Make dataframe of significant ASVs
sig_asvs <- sig_res$ASV
otu_sig <- otu[sig_asvs, , drop = FALSE]

# Ensure same sample order
otu_sig <- otu_sig[, rownames(meta)]

# Extract qPCR 16S load
meta$qpcr_16s_copies_ul <- gsub(",", "", meta$qpcr_16s_copies_ul)
meta$qpcr_16s_copies_ul <- as.numeric(meta$qpcr_16s_copies_ul)
qpcr_16s <- meta$qpcr_16s_copies_ul
names(qpcr_16s) <- rownames(meta)
qpcr_16s <- qpcr_16s[colnames(otu_sig)]

# Normalize abundance by dividing by qPCR copies per ASV
normalized_abundance <- sweep(otu_sig, 2, qpcr_16s, FUN = "/")
```

## Correlation between ASV abundance and Fibrinogen

```{r correlation}
# Regression between concentration and inflammation

# Ensure Fibrinogen is numeric
meta$FIBRINOGEN_MEAN <- as.numeric(meta$FIBRINOGEN_MEAN)

# Keep only samples with qPCR and fibrinogen data
keep_samples <- !is.na(meta$qpcr_16s_copies_ul) & !is.na(meta$FIBRINOGEN_MEAN)
meta <- meta[keep_samples, ]

# Spearman correlation with continuous fibrinogen
fibrino_cor_results <- lapply(rownames(normalized_abundance), function(asv) {
  
  x <- as.numeric(normalized_abundance[asv, ])
  y <- meta$FIBRINOGEN_MEAN
  
  res <- cor.test(x, y, method = "spearman", exact = FALSE)
  
  data.frame(
    ASV = asv,
    Spearman_rho = unname(res$estimate),
    p_value = res$p.value)})

# Combine results into a data frame
fibrino_cor_df <- bind_rows(fibrino_cor_results)

# Merge correlation
Fibrino_cor_annotated <- fibrino_cor_df %>%
  left_join(res_df, by = "ASV") %>%
  left_join(tax_df, by = "ASV")


# Adjust P values
Fibrino_cor_annotated <- Fibrino_cor_annotated %>%
  mutate( cor_padj = p.adjust(p_value, method = "BH")) #Control the False Discovery Rate (FDR) using Benjamini–Hochberg (BH)

# Edit table
Fibrino_cor_annotated <- Fibrino_cor_annotated %>% 
  select(
    ASV,
    Spearman_rho,
    lfcSE,
    stat, 
    p_value, 
    padj, 
    cor_padj,
    log2FoldChange,
    baseMean,
    ends_with(".x")
  ) %>% 
  rename_with(~ sub("\\.x$", "", .x), ends_with(".x"))


# Save results
write.csv(
  Fibrino_cor_annotated,file.path(path.rds,
            "DeSeq_Fibrinogen/Files/Fibrino_qPCR_Spearman_DESeq_Annotated.csv"),
  row.names = FALSE)


```

```{r ASVs_to_plot}
# Identify ASVs of interest (example filter)
Fibrino_cor_annotated <- read.csv(file.path(path.rds,
    "DeSeq_Fibrinogen/Files/Fibrino_qPCR_Spearman_DESeq_Annotated.csv"),header = TRUE)
  
fibrino_hits <- Fibrino_cor_annotated %>%
  filter(abs(Spearman_rho) > 0.2,     
         padj < 0.01) %>%  arrange(desc(abs(Spearman_rho)))

head(fibrino_hits)

## Get a small dataframe of fibrino_hits: only ASV, Spearman_rho, p_value
fibrino_cor_df <- as.data.frame(fibrino_hits) # Ensure base data.frame
fibrino_cor_df$Spearman_rho <- as.numeric(fibrino_cor_df$Spearman_rho)
fibrino_cor_df$p_value     <- as.numeric(fibrino_cor_df$p_value)
fibrino_cor_df_small <- fibrino_cor_df[, c("ASV", "Spearman_rho", "p_value", "Phylum", "Genus",  "baseMean",       "log2FoldChange" ,"lfcSE")]

# Top ASVs by absolute rho
top_hits <- fibrino_cor_df_small[order(-abs(fibrino_cor_df_small$Spearman_rho)), ]
top_hits <- top_hits  %>%  mutate(ASV_label = paste0(ASV, " (", Genus, ")"))
asvs_to_plot <- top_hits %>%  select(ASV, Genus) %>%  distinct()
asvs_to_plot <- asvs_to_plot[asvs_to_plot$ASV %in% rownames(normalized_abundance), ]
asvs_to_plot

# Save results
write.csv(
  asvs_to_plot,file.path(path.rds,
            "DeSeq_Fibrinogen/Files/Fibrino_asvs_to_plot.csv"),
  row.names = FALSE)
```

## Plots

```{r Lollipop-heatmap}
## Lollipop Plot -------------------------------

lollipop_data <- sig_res_sorted %>%
  filter(padj < 0.01 & abs(log2FoldChange) > 2) %>%
  mutate(
    Tax_label = paste0(ASV, " (", Genus, ")"),
    Signif_size = -log10(padj + 1e-10),
    Direction = ifelse(log2FoldChange > 0, 
                       "Enriched in Elevated", 
                       "Enriched in Normal"))

lollipop_data <- lollipop_data %>%
  arrange(log2FoldChange) %>%
  mutate(Tax_label = factor(Tax_label, levels = unique(Tax_label)))
shared_order <- lollipop_data$ASV

lollipop_data <- lollipop_data %>%
  mutate(
    ASV = factor(ASV, levels = shared_order),
    Tax_label = factor(Tax_label, levels = Tax_label)
  )

Genus_list <- unique(lollipop_data$Genus)
Genus_colors <- setNames(
  colorRampPalette(RColorBrewer::brewer.pal(8, "Dark2"))(length(Genus_list)),
  Genus_list)

# Lollipop plot
lollipop_data <- lollipop_data %>%
  mutate( ASV = factor(ASV, levels = shared_order),
          Tax_label = factor(Tax_label, levels = Tax_label)  )


## Heat Map --------------------------------------
estimate.max <- Fibrino_cor_annotated %>% 
  filter(!is.na(Spearman_rho)) %>% 
  .$Spearman_rho %>% 
  abs() %>% 
  max() %>% 
  round(digits = 2)

cor.estimate.ord <- Fibrino_cor_annotated %>% 
  inner_join(Fibrino_cor_annotated %>% select(ASV, Genus), by = "ASV")%>% 
  left_join(select(fibrino_hits, ASV , ASV), by = "ASV")

# order by log2FC (if biology is DESeq2-driven)
cor.estimate.ord <- cor.estimate.ord %>%
  arrange(desc(abs(log2FoldChange))) %>%
  mutate(Plot_Order = row_number())

cor.estimate.ord <- cor.estimate.ord %>%
  mutate(is_hit = ASV %in% fibrino_hits$ASV)

cor.estimate.ord <- cor.estimate.ord %>%
  mutate(
    ASV_label = paste0(ASV, " (", Genus.x, ")"))


colnames(cor.estimate.ord)

# Heatmap a
Heatmap <- ggplot(cor.estimate.ord) +
  geom_tile(
    aes(x = "Correlation", y = reorder(ASV, Plot_Order),
        fill = Spearman_rho ) ) +
  geom_text(
    data = filter(cor.estimate.ord, is_hit),
    aes(x = 1, y = ASV),
    label = "*"  )
Heatmap


```
### Barplot

```{r barplot_fib}
# barplot significant taxa by log2FoldChange ------------------------
barplot.df <- sig_res_sorted %>%
  arrange(desc(abs(log2FoldChange))) %>%
  mutate(
    Taxa  = reorder(ASV, log2FoldChange),
    Genus = ifelse(is.na(Genus) | Genus == "",  paste0("Uncharacterized:", Family), Genus))

label_asvs <- unique(asvs_to_plot$ASV)
y_labels <- setNames(
  ifelse( barplot.df$ASV %in% label_asvs,
          paste0(barplot.df$ASV, " (", barplot.df$Genus, ")"),""),  barplot.df$ASV)

# Plot
barplot <- ggplot(barplot.df, aes(x = log2FoldChange, y = Taxa)) +
  geom_col(aes(fill = log2FoldChange), position = "identity") +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red") +
  geom_text(
    data = dplyr::filter(barplot.df, ASV %in% label_asvs),
    aes(x = 0, y = Taxa, label = paste0("*", ASV, " (", Genus, ")")),
    hjust = 0,  vjust=0,   size = 1 ) +
  scale_y_discrete(labels = y_labels) +
  scale_x_continuous(
    breaks = function(x) seq(
      from = floor(min(x, na.rm = TRUE) / 10) * 10,
      to   = ceiling(max(x, na.rm = TRUE) / 10) * 10,
      by   = 10)) +
  theme_bw() +
  labs(title = "Differentially Abundant Taxa with Fibrinogen") +
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(), 
    legend.position = "bottom"
  )
barplot
```
### Heatmap
```{r Heatmap2}
# Keep same order as the Barplot
ht.cor.estimate.ord <- Fibrino_cor_annotated %>%
  mutate( is_hit = ASV %in% fibrino_hits$ASV) %>%
  arrange(desc(log2FoldChange)) %>%
  mutate(ASV = factor(ASV, levels = ASV))

# Heatmap matrix
mat <- ht.cor.estimate.ord %>%
  select(Spearman_rho) %>%
  as.matrix()
rownames(mat) <- ht.cor.estimate.ord$ASV

# Label significant correlations
sig_mat <- ht.cor.estimate.ord %>%
  mutate(star = ifelse(is_hit, "*", "")) %>%
  select(star) %>%
  as.matrix()

rownames(sig_mat) <- ht.cor.estimate.ord$ASV
colnames(sig_mat) <- colnames(mat)

# Plot settings
rho_lim <- max(abs(ht.cor.estimate.ord$Spearman_rho), na.rm = TRUE)
col_fun <- colorRamp2(c(-rho_lim, 0, rho_lim), c("blue", "white", "red"))

ht_plot <- Heatmap(
  mat,
  name = "Spearman ρ",
  col = col_fun,
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  show_column_names = FALSE,
  show_row_names = FALSE,
  row_title = NULL,
  cell_fun = function(j, i, x, y, width, height, fill) {
    if (sig_mat[i, j] == "*") {
      grid.text("*", x, y, gp = gpar(fontsize = 5, fontface = "bold"))
      grid.text(
        rownames(mat)[i],
        x + unit(0.6, "mm"),
        y,
        just = "left",
        gp = gpar(fontsize = 5)
      )
    }
  }
)
ht_plot

```


```{r Fib_Final_plots}
### Combine plots -------------------------------
# Barplot + Heatmap
ht_grob <- grid.grabExpr(ComplexHeatmap::draw(
    ht_plot, heatmap_legend_side = "bottom",
    padding = unit(c(0, 0, 0, 0), "mm")))

ht_plot <- wrap_elements(full = ht_grob)

final_plot <- barplot + ht_plot +
  plot_layout(widths = c(4, 1), guides = "collect") &
  theme(legend.position = "bottom")

final_plot

ggsave(
  filename = "Fig_4_Fibrinogen_DESeq2_Barplot_Heatmap.svg",
  plot = final_plot,  
  path = file.path(path.figures),
  width = 10,   height = 10,   dpi = 300 )
```


### Individual Correlation Plots
```{r correlation_plots}
# Function to get taxon label (Genus or Class)
get_tax_label <- function(asv, tax) {
  g <- tax[asv, "Genus"]
  f <- tax[asv, "Family"]
  
  if (!is.na(g) && g != "") {
    return(g)  # Use Genus if available
  } else if (!is.na(f) && f != "") {
    return(paste0("Uncharacterized:", f))  # Use Family if Genus missing
  } else {
    return("Taxon: Unknown")  # fallback
  }
}

# Get Plots
plot_list <- list()
for (i in seq_len(nrow(asvs_to_plot))) {
  
  # Extract ASV and genus
  asv <- asvs_to_plot$ASV[i]
  tax_label <- asvs_to_plot$Genus[i]
  
  # Prepare data for plotting
  df_plot <- data.frame(
    Abundance = as.numeric(normalized_abundance[asv, ]),
    Fibrinogen = meta$FIBRINOGEN_MEAN  )
  
  # Remove zero-inflated samples for THIS ASV
  df_plot <- df_plot[df_plot$Abundance > 0, ]
  
  # correlation values
  rho  <- top_hits$Spearman_rho[top_hits$ASV == asv]
  pval <- top_hits$p_value[top_hits$ASV == asv]
  
  # Build the title: ASV + Taxon Name
  plot_title <- paste0(asv, " (", tax_label, ")")
  
  p <- ggplot(df_plot, aes(x = Fibrinogen, y = Abundance)) +
    geom_point(size = 4, alpha = 0.7) +
    geom_smooth(method = "lm", se = FALSE, linewidth = 0.8, color = "black") +
    labs(
      title = bquote(.(asv) ~ "(" * italic(.(tax_label)) * ")"),
      x = "Fibrinogen Mean",
      y = "Normalized Abundance") +
    annotate( "text", x = -Inf, y = Inf,label = deparse(
      bquote(rho == .(round(rho, 3)) ~
               "|" ~ italic(p) == .(signif(pval, 3)))),
      parse = TRUE, hjust = -0.05, vjust = 1.2, size = 3.5) +
    scale_y_continuous(labels = scales::scientific) +
    theme_minimal(base_size = 12)+
    theme(panel.border = element_rect(color = "black", 
                                      fill = NA, linewidth = 0.8))
  
  plot_list[[asv]] <- p


# Save
 ggsave(
    filename = file.path(path.figures, paste0("correlation_", asv, ".svg")),
    plot = p, width = 6, height = 5,  dpi= 300  )}

# Show the first ASV plot
for (i in 1:6) {print(plot_list[[i]])}
```


### Log2 Fold Change Shrinkage

```{r}
# Log2 Fold Change Shrink
res_LFC_fb <- lfcShrink(dds, 
                         type = "ashr", 
                         res = res)

# Filter for significant results
res_LFC_fb <- res_LFC_fb[which(res_LFC_fb$padj < 0.01 & 
                               abs(res_LFC_fb$log2FoldChange) > 2), ]
summary(res_LFC_fb)

# Order LFC results by adjusted P values
res_LFC_fb_df <- as.data.frame(res_LFC_fb[order(res_LFC_fb$padj, na.last = NA), ])
sum(res_LFC_fb_df$padj < 0.01, na.rm = TRUE)

# Keep only KOs with adjusted p-value < 0.01
res_LFC_fb_df <- res_LFC_fb_df[
  res_LFC_fb_df$padj < 0.01 & !is.na(res_LFC_fb_df$padj), ]
dim(res_LFC_fb_df)
0
```

```{r}
head(res_LFC_fb_df)
library(reactable)
library(DT)

res_df <- res_LFC_fb_df
if (!"KOs" %in% colnames(res_df)) {
res_df <- cbind(KOs = rownames(res_df), res_df)
rownames(res_df) <- NULL
}

datatable(
res_df,
extensions = c('Buttons', 'Responsive', 'Scroller'),
options = list(
dom = 'Bfrtip', # show buttons, filter, table
buttons = c('copy', 'csv', 'excel', 'pdf'),
pageLength = 15,
lengthMenu = c(10, 15, 25, 50, 100),
scrollX = TRUE,
scrollY = "400px",
deferRender = TRUE,
scroller = TRUE
),
filter = 'top',
rownames = FALSE,
class = 'stripe hover compact'
)
```
